/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema_de_cine;

import conexion_BD.conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jr245
 */
public class Panel_Clientes extends javax.swing.JPanel {
DefaultTableModel modelo;
    /**
     * Creates new form Panel_Clientes
     */
    public Panel_Clientes() {
        initComponents();
        
        modelo = (DefaultTableModel) clientes.getModel();
        modelo.setRowCount(0);
        
        mostrarClientes();
                
                
    }
    
    private void mostrarClientes() {
    conexion dbc = new conexion(); // creamos la conexion
    Connection con = dbc.conectar(); // abrimos la conexion
    
    Statement st = null;
    ResultSet rs = null;
    
    try {
        st = con.createStatement(); // preparamos la consulta
        rs = st.executeQuery("SELECT * FROM clientes"); // ejecutamos la consulta para obtener todos los clientes
        
        // vamos leyendo cada registro que nos devuelve la consulta
        while (rs.next()) {
            // tomamos todos los datos de la fila y los agregamos en el arreglo fila
            Object[] fila = {
                rs.getInt("cliente_id"),      // el ID del cliente (auto_increment)
                rs.getString("nombre"),       // el nombre del cliente (varchar 50)
                rs.getString("apellido"),     // el apellido del cliente (varchar 50)
                rs.getString("email"),        // el email del cliente (varchar 100, unico)
                rs.getString("telefono")      // el telefono del cliente (varchar 15, puede ser null)
            };
            // añadimos esa fila a la tabla 
            modelo.addRow(fila);
        }
        
    } catch (SQLException ex) {
        // si algo sale mal con la conexion muestra este mensaje en la consola
        System.out.println("Error al cargar clientes: " + ex.getMessage());
    } finally {
        // cerramos todo para liberar memoria y evitar problemas
        try {
            if (rs != null) rs.close();
            if (st != null) st.close();
            if (con != null) con.close();
        } catch (SQLException ex) {
            System.out.println("Error cerrando recursos: " + ex.getMessage());
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        clientes = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 0, 0));

        clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Correo", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(clientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable clientes;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
